[build]
  publish = "."
  command = "echo 'No build step required'"

[[redirects]]
  from = "/health%20website/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/health website/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/patient-dashboard"
  to = "/patient-dashboard.html"
  status = 200

[[redirects]]
  from = "/doctor-dashboard"
  to = "/doctor-dashboard.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
